sonar.projectKey=Hasan26ozcan_Script-Supervisor
sonar.organization=hasan26ozcan

sonar.sources=app
sonar.tests=tests

sonar.python.coverage.reportPaths=coverage.xml

sonar.python.version=3.11
sonar.sourceEncoding=UTF-8
